environment:
  MINICONDA: "C:\\Miniconda"

platform: x86

configuration: Release

init:
  - set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%
  - conda create -n syncplay -y
  - activate syncplay
  - conda install python pywin32 pyside -y
  - pip2 install twisted py2exe_py2 zope.interface
  - type nul > C:\Miniconda\envs\syncplay\lib\site-packages\zope\__init__.py
  - pip2 freeze
  - conda list
  - for /f %%a in ('git describe --tags --abbrev^=0 --match^=v*') do set gittagversion=%%a
  
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - py -2 buildPy2exe.py
  - del syncplay_%gittagversion%\lib\DNSAPI.dll
  - del syncplay_%gittagversion%\lib\MPR.dll
  - mkdir syncplay_%gittagversion%\platforms
  #- copy C:\Miniconda\envs\syncplay\library\plugins\platforms\qwindows.dll C:\projects\syncplay\syncplay_v1.5.0\platforms\

# Not a project with an msbuild file, build done at install.
build: off 

artifacts:
  path: 'syncplay_$(gittagversion)'
  type: zip
  name: Syncplay_win

# Push artefact to S3 bucket and list all
before_deploy:
  - dir
  #- python -c "from PySide2 import QtCore; print QtCore.QLibraryInfo.location(QtCore.QLibraryInfo.PluginsPath)"

# Deploy build to BinTray
deploy:
  provider: BinTray
  username: wiiaboo
  api_key:
    secure: DMsGKl2OCo4WG4xV308z/+W2bNkt91Lc9XIO8ZJWrOzmpuysa1x9zKK/NCWW/z6n
  subject: wiiaboo
  repo: Syncplay
  package: Syncplay
  version: $(gittagversion)
  publish: true
  override: true
